CI script refactory

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -33,6 +33,7 @@ before_script:
 script:
   # Check charts format
   - >
+     set -e # exit if one command fails
      for dir in `ls ${REPO_DIR}/charts`; do
       helm lint ${REPO_DIR}/charts/$dir
      done
@@ -40,7 +41,6 @@ script:
 after_success:
   - >
     if [ $TRAVIS_BRANCH = 'master' ] && [ $TRAVIS_PULL_REQUEST = 'false' ]; then
-    
       # Temporary dir for storing new packaged charts and index files
       BUILD_DIR=$(mktemp -d)
 
@@ -82,23 +82,16 @@ after_success:
       cp $BUILD_DIR/* out/
       cd out
 
-      # Check for changes
-      if [ git diff --quiet ]; then
-       echo "No changes, exiting."
-       exit 0
+      # Deploy if there are some changes
+      git diff --quiet
+      if [ $? != 0 ]; then
+       # Add all new files to staging phase and commit the changes
+       git config user.name "Travis CI"
+       git config user.email "travis@travis-ci.org"
+       git add -A .
+       git status
+       git commit -m "Deploy to test repository ${SHA}"
+       # We can push.
+       git push ${SSH_REPO}
       fi
-
-      # Add all new files to staging phase and commit the changes
-      git config user.name "Travis CI"
-      git config user.email "travis@travis-ci.org"
-      git add -A .
-      git status
-      git commit -m "Deploy to test repository ${SHA}"
-
-      # We can push.
-      git push ${SSH_REPO}
-
-      # Kill ssh-agent process due to current Travis bug
-      # To be removed once bug is fixed
-      ssh-agent -k
     fi
